version: "3"
services:

  poll:
    build: ./poll
    restart: always
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:buster
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    depends_on:
      - "db"
      - "redis"
    restart: always
    networks:
      - back-tier
    environment:
      - "REDIS_HOST=redis"
      - "POSTGRES_HOST=db"
      - "POSTGRES_PASSWORD=password"

  db:
    image: postgres:13.0
    restart: always
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=postgres"

  result:
    build: ./result
    restart: always
    depends_on:
      - "db"
    environment:
      - POSTGRES_HOST=db
    ports:
      - "5001:80"
    networks:
      - result-tier

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: